# Generated by Django 3.2.12 on 2022-02-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Attached_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignee'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(choices=[('operational', 'Operational'), ('frontend', 'Front-end'), ('backend', 'Back-end'), ('design', 'Design')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
