# Generated by Django 3.2.12 on 2022-02-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Urgent'), ('2', 'High'), ('3', 'Normal'), ('4', 'Low')], max_length=100),
        ),
    ]
