# Generated by Django 3.2.12 on 2022-02-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_issue_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Attached_file',
            new_name='attached_file',
        ),
    ]
