# Generated by Django 3.2.12 on 2022-03-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220308_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attached_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
